MODEL:
  LAYERS: [1, 6, 11, 20]

DATASET:
  DATA_ROOT: ./data

IMG_PROCESSING:
  IMSIZE: 512
  CROPSIZE: 256
  CENCROP: False

LOSS:
  FEATURE_WEIGHT: 0.1
  TV_WEIGHT: 1.0

TRAINING:
  MAX_ITER: 5000
  LEARNING_RATE: 0.001
  BATCH_SIZE: 32
  USE_CUDA: True
  CHECK_PER_ITER: 100

OUTPUT:
  CHECKPOINT_PREFIX: avatarnet_batch32_epoch10_1.0e-03
