MODEL:
  USE_DATAPARALLEL: True
  USABLE_GPUS: [1,2,3]

DATASET:
  DATA_ROOT: /tmp2/Avatar-Net/dataset/train2014

IMG_PROCESSING:
  IMSIZE: 512
  CROPSIZE: 256
  CENCROP: False

LOSS:
  FEATURE_WEIGHT: 0.1
  TV_WEIGHT: 1.0

TRAINING:
  MAX_ITER: 5000
  LEARNING_RATE: 0.001
  BATCH_SIZE: 16
  USE_CUDA: True
  CHECK_PER_ITER: 100

OUTPUT:
  CHECKPOINT_PREFIX: avatarnet_batch32_epoch10_1.0e-03
